<form class="form-signin" action="" method="POST" autocomplete="off">
    <h2 class="form-signin-heading">Administration</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <?= $this->form->getElement('username'); ?>
    <label for="inputPassword" class="sr-only">Password</label>
    <?= $this->form->getElement('password'); ?>
    <?= $this->form->getElement('send'); ?>
</form>
