<?php
    $config    = new Zend_Config_Xml(APPLICATION_PATH . '/configs/navigation.xml', 'nav');
    $container = new Zend_Navigation($config);
    $this->navigation($container)->menu()->setUlClass("nav navbar-nav");
?>
<nav class="navbar navbar-default navbar-fixed-top">
    <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Stéphane FÉREY</a>
        </div>
        <canvas id="courbes" class="navbar-right"></canvas>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
            <?= $this->navigation();?>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>