<section id="professional" class="cd-container cd-timeline">
    <div class="cd-header">
        <h1>Expérience</h1>
    </div>
    <?= $this->partialLoop("./formation/partials/item-timeline.phtml", $this->experiences); ?>
</section> <!-- cd-timeline -->
<section id="school" class="cd-container cd-timeline">
    <div class="cd-header">
        <h1>Formation</h1>
    </div>
    <?= $this->partialLoop("./formation/partials/item-timeline.phtml", $this->educations); ?>
</section> <!-- cd-timeline -->