<div class="cd-timeline-block">
    <div class="cd-timeline-img cd-<?= ($this->partialCounter % 2)?"odd":"even";?>">
        <span class="glyphicon glyphicon-briefcase"></span>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
        <h2><?= $this->name ?><br><small><?= $this->business ?></small></h2>
        <p><?= ($this->description != null)?$this->description:false?></p>
        <span class="cd-date"><?= $this->begin?><?= ($this->end == null)?false:($this->end == 'now')?" - Aujourd'hui":" - ".$this->end;?></span>
    </div> <!-- cd-timeline-content -->
</div> <!-- cd-timeline-block -->