<div class="site-wrapper-inner">
    <div class="cover-header">
        <canvas id="courbes"></canvas>
        <h1 class="cover-heading"><?= $this->name ?></h1>
        <h3><?= $this->slogan ?></h3>
    </div>
    <div class="cover-container">
        <div class="inner cover">
            <p class="lead">
                <?php foreach ($this->leads as $lead) {
                    echo $lead . "<br>";
                }?>
            </p>
        </div>
        <a href="/formation" class="btn btn-follow">Follow me <span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
</div>