<!DOCTYPE html>
<html>
<head>
    <link href="/assets/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Share+Tech' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href="/css/styles.css" rel="stylesheet">
</head>
<body>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-header">
            <canvas id="courbes"></canvas>
            <h1 class="cover-heading"><?= $this->name ?></h1>
            <h3><?= $this->slogan ?></h3>
        </div>
        <div class="cover-container">
            <div class="inner cover">
                <p class="lead">
                    <?php foreach ($this->leads as $lead) {
                        echo $lead . "<br>";
                    }?>
                </p>
            </div>
        <a href="/formation" class="btn btn-follow">Follow me <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
</div>

<script language="javascript">
    var canvas = document.getElementById('courbes');
    var ctx = canvas.getContext('2d');
    var numberOfLines = 8;
    var i = 0;
    var cycle = function() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        for(var j=0; j< numberOfLines; ++j) {
            ctx.lineWidth = 1+2*(numberOfLines-j);
            ctx.strokeStyle = 'rgba(100,200,'+Math.floor(Math.abs(Math.cos(i/80)*256))+','+(j/5+0.1)+')';
            var offset = (i+j*10*Math.abs(Math.cos(i/100)))/20;
            var y = (Math.sin(offset)+1)*canvas.height/2;
            var cpy1 = (Math.cos(offset)+0.5)*canvas.height;
            var cpy2 = canvas.height - cpy1;
            ctx.beginPath();
            ctx.moveTo(0, y);
            ctx.bezierCurveTo(canvas.width/3, cpy1, 2*canvas.width/3, cpy2, canvas.width, y);
            ctx.stroke();
        }
        i++;
    };
    setInterval(cycle, 30);

</script>
</body>
</html>
